name: zoho_creator_config
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  dio: ^5.4.1
  email_validator: ^2.1.17
  flutter:
    sdk: flutter
  flutter_otp_text_field: ^1.1.2+1
  flutter_swipe_button: ^2.1.1+1
  image_picker: ^0.8.4+4
  mailer: ^6.1.0
  otp_text_field: ^1.1.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    # - assets/icons/
    # - assets/icons/DarkNewIcons/
